import { chromium } from 'playwright';
const BASE = process.env.BASE_URL || 'http://localhost:5173';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
const who = process.argv[2] ?? 'karen.multiorg@example.com';
await page.goto(BASE + '/login');
await page.locator('body[data-hydrated="true"]').waitFor({ state: 'attached' });
const reveal = page.getByRole('button', { name: 'Show login form' });
if (await reveal.isVisible({ timeout: 3000 }).catch(() => false)) await reveal.click();
await page.getByLabel('Email address').fill(who);
await page.getByLabel('Password', { exact: true }).fill('password123');
await page.getByRole('button', { name: 'Sign in', exact: true }).click();
await page.waitForURL(/\/dashboard(\/|$|\?)/, { timeout: 20000 });
await page.goto(BASE + '/events/revel-events-collective/classical-music-evening');
await page.locator('body[data-hydrated="true"]').waitFor({ state: 'attached' });
await page.getByRole('button', { name: 'Open notifications' }).waitFor({ timeout: 20000 });
await page.waitForTimeout(3000);
const region = page.getByRole('region', { name: 'Ticket Options' });
console.log('--- Ticket Options text ---');
console.log((await region.innerText().catch(() => 'REGION NOT FOUND')).slice(0, 1500));
console.log('--- buttons on page ---');
for (const b of await page.getByRole('button').allInnerTexts()) if (b.trim()) console.log('*', b.trim().slice(0, 60));
await browser.close();
